[package]
name = "rpass"
version = "0.1.0"
authors = ["Miroslav Svitok <mirosvitok@gmail.com>"]
build = "build.rs"

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
getopts = "0.2"
libc = "0.1.10"
rand = "0.3.11"
rust-crypto = "*"

[build-dependencies]
gcc = "0.3"
